### PR TITLE
Add command traits.

### PR DESCRIPTION
**Pull request by Jelle-S**

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
I presume this works? I did not try it, but I remember at one point someone said something about commands not being recognized when defined in traits.

The general Robo model is to provide commands in the RoboFile, and building-blocks for commands in external projects. The typical way to do this would be to provide tasks to perform all of these functions, and then call them from a trivial command that initializes the tasks from the command arguments and options.

If you're not running into any bugs & this is working fine, there is no rule that says you can't provide commands this way. PHP will allow you to override traits from classes that `use` them, so you could in theory even override your trait commands from your RoboFile -- although I don't know how the annotation parser would react if you did this.

Overall, though, this use pattern implies that what you are trying to do is build multiple tools that all contain the same Robo commands. I presume you want to do this because you are defining Robo scripts in your composer.json file, and you want to be able to add site-specific build commands to your RoboFile, and also pull in standard commands from your command "libraries". This seems fine to me. In fact, if this method works well for you, it might be worthwhile documenting this as a recommended usage model, analogous to the [Robo as a Framework](http://robo.li/framework/) document.

**Comment by daften** [comment]
We still need to test this, that was planned for this week, but unfortunately, flu season is here, so we didn't get around to it.
If this model works properly, and we can override commands locally, we'll document the pattern as suggested.
Thanks for the feedback, much appreciated!

**Comment by greg-1-anderson** [comment]
If the commands in traits are ignored, it might take more work in the annotated-commands library to make them functional. Any efforts in this direction should be carefully considered in terms of performance, and interoperability with the existing CommandInfo cache.

**Comment by Jelle-S** [comment]
@greg-1-anderson Seems to work fine with the trait:

```
$ vendor/bin/robo list
Robo 1.0.5

Usage:
  command [options] [arguments]

Options:
  -h, --help                           Display this help message
  -q, --quiet                          Do not output any message
  -V, --version                        Display this application version
      --ansi                           Force ANSI output
      --no-ansi                        Disable ANSI output
  -n, --no-interaction                 Do not ask any interactive question
      --simulate                       Run in simulated mode (show what would have happened).
      --progress-delay=PROGRESS-DELAY  Number of seconds before progress bar is displayed in long-running task collections. Default: 2s. [default: 2]
  -v|vv|vvv, --verbose                 Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help                       Displays help for a command
  list                       Lists commands
  test                       Runs the unit tests.
 digipolis
  digipolis:package-project  
  digipolis:theme-clean      
  digipolis:theme-compile    
```

**Pull request merged**
